// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXptUIMIJbqnuvVbPMYOvwsgrmrwt8nU',
    appId: '1:115861207764:web:7ad2cd69572d7608965941',
    messagingSenderId: '115861207764',
    projectId: 'fooodak-6d5c3',
    authDomain: 'fooodak-6d5c3.firebaseapp.com',
    storageBucket: 'fooodak-6d5c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHgFuGop_HszZTkW4DkTWqzOqFcJ9xTxM',
    appId: '1:115861207764:android:b698fc2eb41abfb6965941',
    messagingSenderId: '115861207764',
    projectId: 'fooodak-6d5c3',
    storageBucket: 'fooodak-6d5c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCE8waqG52DnWWw58dPQZwa5tgpcky7Y',
    appId: '1:115861207764:ios:231bfdf9cb40122d965941',
    messagingSenderId: '115861207764',
    projectId: 'fooodak-6d5c3',
    storageBucket: 'fooodak-6d5c3.appspot.com',
    iosClientId: '115861207764-2jnpo6bkcmm1s9lbbkvog2mcopqmcdeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQCE8waqG52DnWWw58dPQZwa5tgpcky7Y',
    appId: '1:115861207764:ios:231bfdf9cb40122d965941',
    messagingSenderId: '115861207764',
    projectId: 'fooodak-6d5c3',
    storageBucket: 'fooodak-6d5c3.appspot.com',
    iosClientId: '115861207764-2jnpo6bkcmm1s9lbbkvog2mcopqmcdeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
